services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    depends_on:
      - php-fpm
    ports:
      - 8080:80
    networks:
      - frontend
    volumes:
      - wp-data:/var/www/html

  php-fpm:
    build: ./requirements/wordpress
    container_name: php-fpm
    restart: always
    depends_on:
      - mariadb
    networks:
      - frontend
      - backend
    volumes:
      - wp-data:/var/www/html
    env_file:
      - ./config/.env
    secrets:
      - passwords

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    networks:
      - backend
    volumes:
      - db-data:/var/lib/mysql
    env_file:
      - ./config/.env
    secrets:
      - passwords 

networks:
  frontend:
  backend:

volumes:
  wp-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/eazmir/data/wp-data
  db-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/eazmir/data/db-data

secrets:
  passwords:
    file: ./secrets/passwords

