services:
  nginx:
    image: nginx
    build: ./requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - 443:443
    networks:
      - frontend
    volumes:
      - wp-data:/var/www/html

  wordpress:
    image: wordpress
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    depends_on:
      - mariadb
    networks:
      - frontend
      - backend
    volumes:
      - wp-data:/var/www/html
    env_file:
      - ../config/.env
    secrets:
      - credentials
      - db_password

  mariadb:
    image: mariadb
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    networks:
      - backend
    volumes:
      - db-data:/var/lib/mysql
    env_file:
      - ../config/.env
    secrets:
      - db_password
      - db_root_password

networks:
  frontend:
  backend:

volumes:
  wp-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/eazmir/data/wp-data
  db-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/eazmir/data/db-data

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  credentials:
    file: ../secrets/credentials.txt