CREATE USER IF NOT EXISTS '$DATABASE_USER'@'%' IDENTIFIED BY '$DB_PASSWORD';
CREATE DATABASE IF NOT EXISTS $DATABASE_NAME;

GRANT ALL PRIVILEGES ON $DATABASE_NAME.* TO '$DATABASE_USER'@'%';
ALTER USER 'root'@'localhost' IDENTIFIED BY '$DB_PASSWORD';

GRANT ALL PRIVILEGES ON $DATABASE_NAME.* TO 'root'@'localhost';
FLUSH PRIVILEGES;