-- CREATE USER IF NOT EXISTS 'eazmir'@'%' IDENTIFIED BY '$DB_PASSWORD';
-- CREATE DATABASE IF NOT EXISTS wp_db;
-- GRANT ALL PRIVILEGES ON wp_db.* TO 'eazmir'@'%';

-- ALTER USER 'root'@'localhost' IDENTIFIED BY 'lx01';
-- GRANT ALL PRIVILEGES ON wp_db.* TO 'root'@'localhost';

-- FLUSH PRIVILEGES; 
CREATE USER IF NOT EXISTS 'eazmir'@'%' IDENTIFIED BY '$DB_PASSWORD';
CREATE DATABASE IF NOT EXISTS wp_db;
GRANT ALL PRIVILEGES ON wp_db.* TO 'eazmir'@'%';
ALTER USER 'root'@'localhost' IDENTIFIED BY '$DB_PASSWORD';
GRANT ALL PRIVILEGES ON wp_db.* TO 'root'@'localhost';
FLUSH PRIVILEGES;